import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import ApiAuthBridge from "@/components/auth/ApiAuthBridge";
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <ApiAuthBridge />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
